### ISSUE TITLE
Jorge Luis Hernandez Matra infografia

### ISSUE THREAD

**Issue by JORGELUIS2266** [SistemasTecTlaxiaco/actividad-1-infografia-JORGELUIS2266#2]
![1](https://github.com/user-attachments/assets/87e4f3b4-f1a4-445b-b8e8-68cc7654aa44)
![2](https://github.com/user-attachments/assets/5a1ebc9a-315f-42f6-b7ff-2de0d9507198)

**Comment by Roldanuriel** [comment]
20/20 cumple con todas las características de la rubrica y describe cada uno de los puntos.

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
